linters:
  enable:
    - errcheck
    - goimports
    - govet
    - staticcheck
    - gosec
    - revive
    - bodyclose
    - gocritic
    - gofumpt

linters-settings:
  gofumpt:
    extra-rules: true
  govet:
    shadow: true
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
