// Code generated by MockGen. DO NOT EDIT.
// Source: external_interface.go
//
// Generated by this command:
//
//	mockgen -source=external_interface.go -destination=../mock/usecase/external_interface.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase
